### PR TITLE
119 edit dog styling

### PR DESCRIPTION
**Pull request by mbostwick1**

### CODE REVIEW

**Comment by mbostwick1** [comment]
Not sure why there is a conflict... please use the updated. :)

**Review by raiford2530 — DISMISSED** [review]
Your code is breaking the upload feature of the edit page.

**Comment by mbostwick1** [comment]
> Your code is breaking the upload feature of the edit page.

Should be good now! :D

**Review by reanderson89 — APPROVED** [review]
[WIP] picture is updated when uploaded and not when form is submitted.

**Pull request merged**
